In [2]:
import pandas as pd

### Задача №1

In [5]:
data = pd.read_csv('/Users/kseniagorchakova/Library/Mobile Documents/com~apple~CloudDocs/Education/!Profession_DS/Python/Python_repository/data/ml-25m/ratings.csv')

In [6]:
data.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [11]:
# Фильтруем данные по признаку rating = 5
rating_5 = data[ (data['rating'] == 5.0) ]

In [19]:
# Считаем ко-во значений по столбку movieId
rating_5['movieId'].value_counts().head(1)

318    39553
Name: movieId, dtype: int64

### Задача №2

In [20]:
power = pd.read_csv('/Users/kseniagorchakova/Library/Mobile Documents/com~apple~CloudDocs/Education/!Profession_DS/Python/Numpy_Pandas_Лекции и семинары/Лекция_2_Pandas_доп.материалы/power.csv')

In [21]:
power.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [31]:
# Фильтрация строк по странам и потреблению больше или равно 0
filtered_countries = power[ (power['country']=='Latvia') | (power['country']=='Lithuania') | (power['country']=='Estonia') & (power['quantity'] >= 0) ]

In [34]:
# Суммирование потребления в отфильтрованном датафрейме
filtered_countries['quantity'].sum()

118002297.8915407

### Задача №3

In [19]:
info = pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8')[1]

In [20]:
info

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,1007819,-,1002850,"0,50 %",04969,22:49:00
1,NaN,EUR/RUB,865925,-,861470,"0,52 %",04455,22:49:00
2,NaN,USD/RUB,727695,-,722358,"0,74 %",05337,22:49:00
3,NaN,JPY/RUB,06582,-,06530,"0,80 %",00052,22:49:00
4,NaN,CNY/RUB,112569,-,111888,"0,61 %",00681,22:49:00
5,NaN,CHF/RUB,790003,-,785428,"0,58 %",04575,22:49:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,11899,-,11926,"-0,23 %",-00027,22:49:00
8,NaN,EUR/GBP,08592,-,08594,"-0,01 %",-00001,22:49:00
9,NaN,EUR/JPY,1315400,-,1319100,"-0,28 %",-03700,22:49:00
10,NaN,EUR/CHF,10961,-,10971,"-0,09 %",-00010,22:49:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,08404,-,08385,"0,23 %",00019,22:49:00
13,NaN,USD/GBP,07221,-,07203,"0,25 %",00018,22:49:00
14,NaN,USD/JPY,1105500,-,1105950,"-0,04 %",-00450,22:49:00
15,NaN,USD/CHF,09210,-,09198,"0,14 %",00013,22:49:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),07600,-,07600,"0,30 %",00000,22:49:00
18,NaN,JPY/GBP,00065,-,00065,"0,31 %",00000,22:49:00
19,NaN,JPY/USD,00091,-,00090,"0,06 %",00000,22:49:00
20,NaN,JPY/CHF (100:1),08300,-,08300,"0,19 %",00000,22:49:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,13849,-,13881,"-0,23 %",-00032,22:49:00
23,NaN,GBP/JPY,1531021,-,1535738,"-0,31 %",-04717,22:49:00
24,NaN,GBP/EUR,11638,-,11640,"-0,02 %",-00002,22:48:00
25,NaN,GBP/CHF,12755,-,12766,"-0,08 %",-00011,22:49:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,12755,-,12766,"-0,08 %",-00011,22:49:00
28,NaN,EUR/CHF,10961,-,10971,"-0,09 %",-00010,22:49:00
29,NaN,JPY/CHF (100:1),08300,-,08300,"0,19 %",00000,22:49:00
30,NaN,USD/CHF,09210,-,09198,"0,14 %",00013,22:49:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,324025,-,325951,"-0,59 %",-01927,22:49:00
33,NaN,USD/UAH,272301,-,273300,"-0,37 %",-00999,22:49:00
34,NaN,CHF/UAH,295626,-,297162,"-0,52 %",-01536,22:48:00
35,NaN,GBP/UAH,377137,-,379422,"-0,60 %",-02286,22:49:00

In [21]:
type(info)

pandas.core.frame.DataFrame